name:                cv-static
version:             0.1.0.0
github:              "mstksg/cv-static"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/cv-static#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- dhall >= 1.29
- hakyll

library:
  source-dirs: src
  dependencies:
  - blaze-html
  - data-default
  - filepath
  - hakyll-dhall
  - hakyll-sass
  - hsass
  - pandoc
  - text
  - th-printf

executables:
  cv-static:
    main:                site.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cv-static

# tests:
#   cv-static-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - cv-static
